obstacle_range: 2.5
raytrace_range: 3
footprint: [[0.7, 0.5], [0.7, -0.5], [-0.7, 0.5],[-0.7,0.5]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources:  laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: optical_cam_center, data_type: PointCloud2, topic: /camera/depth/fakepoints, marking: true, clearing: true}