local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  #plugins:
  # {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
  
  update_frequency: 10
  publish_frequency: 10
  static_map: false
  rolling_window: true
  width: 20
  height: 20
  origin_x: -10
  origin_y: -10
  resolution: .05